################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
S_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
OBJS := 
C_DEPS := 
ASM_DEPS := 
ARCHIVES := 
LSS := 
S_DEPS := 
SIZEDUMMY := 
S_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src \
src/wifishield/wifi_dnld/src \
src/wifishield/wifi_dnld/src/SOFTWARE_FRAMEWORK/UTILS/DEBUG \
src/wifishield/wifi_dnld/src/SOFTWARE_FRAMEWORK/SERVICES/MEMORY/CTRL_ACCESS \
src/wifishield/wifi_dnld/src/SOFTWARE_FRAMEWORK/DRIVERS/USART \
src/wifishield/wifi_dnld/src/SOFTWARE_FRAMEWORK/DRIVERS/SPI \
src/wifishield/wifi_dnld/src/SOFTWARE_FRAMEWORK/DRIVERS/PM \
src/wifishield/wifi_dnld/src/SOFTWARE_FRAMEWORK/DRIVERS/INTC \
src/wifishield/wifi_dnld/src/SOFTWARE_FRAMEWORK/DRIVERS/GPIO \
src/wifishield/wifi_dnld/src/SOFTWARE_FRAMEWORK/DRIVERS/FLASHC \
src/wifishield/wifi_dnld/src/SOFTWARE_FRAMEWORK/COMPONENTS/MEMORY/DATA_FLASH/AT45DBX \
src/wifishield/wifi_dnld/src/SOFTWARE_FRAMEWORK/BOARDS/EVK1105 \
src/wifishield/wifi_dnld/src/SOFTWARE_FRAMEWORK/BOARDS/ARDUINO \
src/wifishield/wifiHD/src \
src/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/UTILS/DEBUG \
src/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/SERVICES/MEMORY/CTRL_ACCESS \
src/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/SERVICES/LWIP/lwip-port-1.3.2/HD/if/netif \
src/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/SERVICES/LWIP/lwip-1.3.2/src/netif \
src/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/SERVICES/LWIP/lwip-1.3.2/src/core \
src/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/SERVICES/LWIP/lwip-1.3.2/src/core/ipv4 \
src/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/SERVICES/DELAY \
src/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/USART \
src/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/TC \
src/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/SPI \
src/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/RTC \
src/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/PM \
src/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/PDCA \
src/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/INTC \
src/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/GPIO \
src/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/FLASHC \
src/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/EIC \
src/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/EBI/SMC \
src/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/COMPONENTS/MEMORY/DATA_FLASH/AT45DBX \
src/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/BOARDS/EVK1105 \
src/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/BOARDS/ARDUINO \
src/wifi_dnld/src \
src/wifi_dnld/src/SOFTWARE_FRAMEWORK/UTILS/DEBUG \
src/wifi_dnld/src/SOFTWARE_FRAMEWORK/SERVICES/MEMORY/CTRL_ACCESS \
src/wifi_dnld/src/SOFTWARE_FRAMEWORK/DRIVERS/USART \
src/wifi_dnld/src/SOFTWARE_FRAMEWORK/DRIVERS/SPI \
src/wifi_dnld/src/SOFTWARE_FRAMEWORK/DRIVERS/PM \
src/wifi_dnld/src/SOFTWARE_FRAMEWORK/DRIVERS/INTC \
src/wifi_dnld/src/SOFTWARE_FRAMEWORK/DRIVERS/GPIO \
src/wifi_dnld/src/SOFTWARE_FRAMEWORK/DRIVERS/FLASHC \
src/wifi_dnld/src/SOFTWARE_FRAMEWORK/COMPONENTS/MEMORY/DATA_FLASH/AT45DBX \
src/wifi_dnld/src/SOFTWARE_FRAMEWORK/BOARDS/EVK1105 \
src/wifi_dnld/src/SOFTWARE_FRAMEWORK/BOARDS/ARDUINO \
src/wifiHD/src \
src/wifiHD/src/SOFTWARE_FRAMEWORK/UTILS/DEBUG \
src/wifiHD/src/SOFTWARE_FRAMEWORK/SERVICES/MEMORY/CTRL_ACCESS \
src/wifiHD/src/SOFTWARE_FRAMEWORK/SERVICES/LWIP/lwip-port-1.3.2/HD/if/netif \
src/wifiHD/src/SOFTWARE_FRAMEWORK/SERVICES/LWIP/lwip-1.3.2/src/netif \
src/wifiHD/src/SOFTWARE_FRAMEWORK/SERVICES/LWIP/lwip-1.3.2/src/core \
src/wifiHD/src/SOFTWARE_FRAMEWORK/SERVICES/LWIP/lwip-1.3.2/src/core/ipv4 \
src/wifiHD/src/SOFTWARE_FRAMEWORK/SERVICES/DELAY \
src/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/USART \
src/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/TC \
src/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/SPI \
src/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/RTC \
src/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/PM \
src/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/PDCA \
src/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/INTC \
src/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/GPIO \
src/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/FLASHC \
src/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/EIC \
src/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/EBI/SMC \
src/wifiHD/src/SOFTWARE_FRAMEWORK/COMPONENTS/MEMORY/DATA_FLASH/AT45DBX \
src/wifiHD/src/SOFTWARE_FRAMEWORK/BOARDS/EVK1105 \
src/wifiHD/src/SOFTWARE_FRAMEWORK/BOARDS/ARDUINO \
src/tools/avr/lib/avr/lib \
src/tools/avr/lib/avr/lib/avrxmega7 \
src/tools/avr/lib/avr/lib/avrxmega5 \
src/tools/avr/lib/avr/lib/avr6 \
src/tools/avr/lib/avr/lib/avr51 \
src/tools/avr/lib/avr/lib/avr5 \
src/tools/avr/lib/avr/lib/avr4 \
src/tools/avr/lib/avr/lib/avr35 \
src/tools/avr/lib/avr/lib/avr31 \
src/tools/avr/lib/avr/lib/avr3 \
src/tools/avr/lib/avr/lib/avr25 \
src/stk500v2 \
src/src/netif \
src/src/core \
src/src/core/ipv4 \
src/robot \
src/optiboot \
src/lwip-port-1.3.2/HD/if/netif \
src/lwip-1.3.2/src/netif \
src/lwip-1.3.2/src/core \
src/lwip-1.3.2/src/core/ipv4 \
src/lilypad/src \
src/lib \
src/lib/avrxmega7 \
src/lib/avrxmega5 \
src/lib/avr6 \
src/lib/avr51 \
src/lib/avr5 \
src/lib/avr4 \
src/lib/avr35 \
src/lib/avr31 \
src/lib/avr3 \
src/lib/avr25 \
src/firmwares/wifishield/wifi_dnld/src \
src/firmwares/wifishield/wifi_dnld/src/SOFTWARE_FRAMEWORK/UTILS/DEBUG \
src/firmwares/wifishield/wifi_dnld/src/SOFTWARE_FRAMEWORK/SERVICES/MEMORY/CTRL_ACCESS \
src/firmwares/wifishield/wifi_dnld/src/SOFTWARE_FRAMEWORK/DRIVERS/USART \
src/firmwares/wifishield/wifi_dnld/src/SOFTWARE_FRAMEWORK/DRIVERS/SPI \
src/firmwares/wifishield/wifi_dnld/src/SOFTWARE_FRAMEWORK/DRIVERS/PM \
src/firmwares/wifishield/wifi_dnld/src/SOFTWARE_FRAMEWORK/DRIVERS/INTC \
src/firmwares/wifishield/wifi_dnld/src/SOFTWARE_FRAMEWORK/DRIVERS/GPIO \
src/firmwares/wifishield/wifi_dnld/src/SOFTWARE_FRAMEWORK/DRIVERS/FLASHC \
src/firmwares/wifishield/wifi_dnld/src/SOFTWARE_FRAMEWORK/COMPONENTS/MEMORY/DATA_FLASH/AT45DBX \
src/firmwares/wifishield/wifi_dnld/src/SOFTWARE_FRAMEWORK/BOARDS/EVK1105 \
src/firmwares/wifishield/wifi_dnld/src/SOFTWARE_FRAMEWORK/BOARDS/ARDUINO \
src/firmwares/wifishield/wifiHD/src \
src/firmwares/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/UTILS/DEBUG \
src/firmwares/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/SERVICES/MEMORY/CTRL_ACCESS \
src/firmwares/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/SERVICES/LWIP/lwip-port-1.3.2/HD/if/netif \
src/firmwares/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/SERVICES/LWIP/lwip-1.3.2/src/netif \
src/firmwares/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/SERVICES/LWIP/lwip-1.3.2/src/core \
src/firmwares/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/SERVICES/LWIP/lwip-1.3.2/src/core/ipv4 \
src/firmwares/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/SERVICES/DELAY \
src/firmwares/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/USART \
src/firmwares/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/TC \
src/firmwares/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/SPI \
src/firmwares/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/RTC \
src/firmwares/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/PM \
src/firmwares/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/PDCA \
src/firmwares/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/INTC \
src/firmwares/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/GPIO \
src/firmwares/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/FLASHC \
src/firmwares/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/EIC \
src/firmwares/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/DRIVERS/EBI/SMC \
src/firmwares/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/COMPONENTS/MEMORY/DATA_FLASH/AT45DBX \
src/firmwares/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/BOARDS/EVK1105 \
src/firmwares/wifishield/wifiHD/src/SOFTWARE_FRAMEWORK/BOARDS/ARDUINO \
src/firmwares/atmegaxxu2/arduino-usbserial \
src/firmwares/atmegaxxu2/arduino-usbdfu \
src/cores/robot \
src/cores/arduino \
src/cores/arduino/avr-libc \
src/caterina-LilyPadUSB \
src/caterina-Arduino_Robot \
src/caterina \
src/bt \
src/bootloaders/stk500v2 \
src/bootloaders/optiboot \
src/bootloaders/lilypad/src \
src/bootloaders/caterina-LilyPadUSB \
src/bootloaders/caterina-Arduino_Robot \
src/bootloaders/caterina \
src/bootloaders/bt \
src/bootloaders/atmega8 \
src/bootloaders/atmega \
src/avr-libc \
src/atmegaxxu2/arduino-usbserial \
src/atmegaxxu2/arduino-usbdfu \
src/atmega8 \
src/atmega \
src/arduino-usbserial \
src/arduino-usbdfu \
src/arduino \
src/arduino/avr-libc \
src/Wire/utility \
src/WiFi/utility \
src/UTILS/DEBUG \
src/USART \
src/TFT/utility \
src/TC \
src/SPI \
src/SOFTWARE_FRAMEWORK/UTILS/DEBUG \
src/SOFTWARE_FRAMEWORK/SERVICES/MEMORY/CTRL_ACCESS \
src/SOFTWARE_FRAMEWORK/DRIVERS/USART \
src/SOFTWARE_FRAMEWORK/DRIVERS/SPI \
src/SOFTWARE_FRAMEWORK/DRIVERS/PM \
src/SOFTWARE_FRAMEWORK/DRIVERS/INTC \
src/SOFTWARE_FRAMEWORK/DRIVERS/GPIO \
src/SOFTWARE_FRAMEWORK/DRIVERS/FLASHC \
src/SOFTWARE_FRAMEWORK/COMPONENTS/MEMORY/DATA_FLASH/AT45DBX \
src/SOFTWARE_FRAMEWORK/BOARDS/EVK1105 \
src/SOFTWARE_FRAMEWORK/BOARDS/ARDUINO \
src/SMC \
src/SERVICES/MEMORY/CTRL_ACCESS \
src/Robot_Control/utility \
src/Robot_Control \
src/RTC \
src/PM \
src/PDCA \
src/MEMORY/DATA_FLASH/AT45DBX \
src/LWIP/lwip-port-1.3.2/HD/if/netif \
src/LWIP/lwip-1.3.2/src/netif \
src/LWIP/lwip-1.3.2/src/core \
src/LWIP/lwip-1.3.2/src/core/ipv4 \
src/INTC \
src/HD/if/netif \
src/GPIO \
src/FLASHC \
src/EVK1105 \
src/EIC \
src/EBI/SMC \
src/DRIVERS/USART \
src/DRIVERS/SPI \
src/DRIVERS/PM \
src/DRIVERS/INTC \
src/DRIVERS/GPIO \
src/DRIVERS/FLASHC \
src/DELAY \
src/DEBUG \
src/DATA_FLASH/AT45DBX \
src/CTRL_ACCESS \
src/COMPONENTS/MEMORY/DATA_FLASH/AT45DBX \
src/BOARDS/EVK1105 \
src/BOARDS/ARDUINO \
src/AT45DBX \
src/ARDUINO \

